controller:
  kind: DaemonSet
  hostPort:
    enabled: true
  extraArgs:
    default-ssl-certificate: "default/main-ingress-cert"
  config:
    hsts: "true"
    hsts-include-subdomains: "true"
    hsts-preload: "true"
    use-geoip: "false"
