apiVersion: v1
kind: Secret
metadata:
  namespace: test
  name: test-secret
type: Opaque
stringData:
  hello: world
  version: "3"
  hi: "yes"

---
apiVersion: v1
kind: Namespace
metadata:
  name: test2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-copy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-copy
  template:
    metadata:
      labels:
        app: secret-copy
    spec:
      containers:
        - name: secret-copy
          image: ghcr.io/micromaomao/secret-copy
          args:
            - "-config"
            - "/config/config.yaml"
          resources:
            requests:
              memory: "1M"
              cpu: "1m"
            limits:
              memory: "100M"
              cpu: "5m"
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          configMap:
            name: secret-copy-config
      serviceAccountName: secret-copy

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: test
  name: secret-copy

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: test
  name: secret-copy-role-binding
subjects:
  - kind: ServiceAccount
    name: secret-copy
    namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-copy-allow-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: secret-copy-allow-access
rules:
  - verbs: ["get", "watch", "list"]
    apiGroups: [""]
    resources: ["secrets"]
    resourceNames: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: test2
  name: secret-copy-role-binding
subjects:
  - kind: ServiceAccount
    name: secret-copy
    namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-copy-allow-patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test2
  name: secret-copy-allow-patch
rules:
  - verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    apiGroups: [""]
    resources: ["secrets"]
    resourceNames: []

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: test
  name: secret-copy-config
data:
  config.yaml: |
    namespace: test
    copyMap:
      test-secret: test2
