apiVersion: v1
kind: Namespace
metadata:
  name: secret-copy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: secret-copy
  name: secret-copy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-copy
  template:
    metadata:
      labels:
        app: secret-copy
    spec:
      containers:
        - name: secret-copy
          image: registry.digitalocean.com/maowtm-images/secret-copy
          args:
            - "-config"
            - "/config/config.yaml"
          resources:
            requests:
              memory: "1M"
              cpu: "1m"
            limits:
              memory: "100M"
              cpu: "5m"
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          configMap:
            name: secret-copy-config
      serviceAccountName: secret-copy

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: secret-copy
  name: secret-copy
imagePullSecrets:
  - name: maowtm-images

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: secret-copy
  name: secret-copy-role-binding
subjects:
  - kind: ServiceAccount
    name: secret-copy
    namespace: secret-copy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-copy-allow-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secret-copy
  name: secret-copy-allow-access
rules:
  - verbs: ["get", "watch", "list"]
    apiGroups: [""]
    resources: ["secrets"]
    resourceNames: []

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: secret-copy
  name: secret-copy-config
data:
  config.yaml: |
    namespace: secret-copy
    copyMap: {}

---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   namespace: test2
#   name: secret-copy-role-binding
# subjects:
#   - kind: ServiceAccount
#     name: secret-copy
#     namespace: secret-copy
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: secret-copy-allow-patch
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: test2
#   name: secret-copy-allow-patch
# rules:
#   - verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
#     apiGroups: [""]
#     resources: ["secrets"]
#     resourceNames: []
