apiVersion: v1
kind: Service
metadata:
  name: bellclone-ws
  namespace: default
spec:
  ports:
  - name: ws
    port: 5000
  selector:
    app: bellclone-ws

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bellclone-ws
  namespace: default
spec:
  selector:
    matchLabels:
      app: bellclone-ws
  template:
    metadata:
      labels:
        app: bellclone-ws
    spec:
      containers:
      - name: app
        image: ghcr.io/micromaomao/bellclone-ws:latest
        ports:
        - name: ws
          containerPort: 5000
        resources:
          requests:
            cpu: 5m
            memory: 5Mi
